### ISSUE TITLE
Syntax for local wallpapers 

### ISSUE THREAD

**Issue by walrus543** [ksyko/wanda#25]
Hello
Could you please give the exact syntax for /storage/emulated/0/Pictures/Wallpapers for example?

I also tried from Termux: storage/pictures/Wallpapers.
Thank you.

**Comment by ksh-b** [comment]
This issue also seems limited to termux. 
`termux-wallpaper -f /path/to/image/' does not work

This is how you would set the wallpaper
`wanda -sl -t /home/kshib/wallpapers/`

**Comment by walrus543** [comment]
All good with `wanda -sl -t storage/pictures/Wallpapers`.
Thank you.
