### ISSUE TITLE
Stuck when applying the wallpaper

### ISSUE THREAD

**Issue by walrus543** [ksyko/wanda#26]
Hello,

I tried the basic syntax using **Wallhaven** but I'm stuck:
![image](https://github.com/ksh-b/wanda/assets/5938828/53140ed0-bc2d-4536-a051-c1284cd0228c)

The wallpaper is not applied.
Thank you for your help.

**Comment by ksh-b** [comment]
Hi,
This seems to be issue with termux-wallpaper (which wanda uses to set wallpaper in termux).
I tried like this, and that seems to be stuck too: 
`termux-wallpaper -u https://w.wallhaven.cc/full/85/wallhaven-858v9j.jpg`

**Comment by ksh-b** [comment]
I'll check if there is any workaround or anything im missing.

**Comment by ksh-b** [comment]
I was missing something. Possibly termux-api. You will need the [app](https://github.com/termux/termux-api).
Could you try this after installing the app
```
pkg up
pkg in termux-api
```

If that doesn't work check out the updated [installation steps](https://github.com/ksh-b/wanda#installation--update) for termux. I was able to get wanda working after following these steps.

But if still doesn't work for you, let me know.

**Comment by walrus543** [comment]
It works well now! Thank you.
I had to install Termux:tasker from Github since I already installed Termux app from Github.
